### ISSUE TITLE
User review on 3/6's draft

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-rest-cdi#30]
Anna was requested to do the user review. She found these issues: 

        1. If I copy the first `git clone` and `cd ... ` commands from the site using 'copied to clipboard' button and then paste into terminal, it asks me for a password to the repo. Maybe it doesn't copy the commands correctly. If I do the same thing manually, i.e. get the ssh url from girhub, do `git clone` in terminal manually, then cd the cloned repo, then no problem.
         
        => Clarified. 
           
        2. After going through the steps of building the app in the start folder and running `mvn install` in the directory, I get the following error:
         
        [INFO] ------------------------------------------------------------------------
        [INFO] BUILD FAILURE
        [INFO] ------------------------------------------------------------------------
        [INFO] Total time: 7.387 s
        [INFO] Finished at: 2018-03-06T14:18:05-05:00
        [INFO] Final Memory: 22M/301M
        [INFO] ------------------------------------------------------------------------
        [ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test (integration-test) on project io.openliberty.guides.cdi-intro: Execution integration-test of goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test failed: There was an error in the forked process
        [ERROR] java.lang.RuntimeException: Unable to create test class 'it.io.openliberty.guides.inventory..gitkeep'
        [ERROR]     at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:135)
        [ERROR]     at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:95)
        [ERROR]     at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:222)
        [ERROR]     at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:107)
        [ERROR]     at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
        [ERROR]     at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        [ERROR]     at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
        [ERROR] Caused by: java.lang.ClassNotFoundException: it.io.openliberty.guides.inventory..gitkeep
        [ERROR]     at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        [ERROR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        [ERROR]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        [ERROR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        [ERROR]     at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
        [ERROR]     ... 6 more
         
        It seems that the test/java/it/io/openliberty/guides/inventory path in 'start' has .gitkeep file that does not exist in the corresponding path of the 'finish'.
         
        => Working on fix. 
         
        3. Further on, the guide states to create 'EndpointTest.java', but the finish folder has 'InventoryEndpointTest.java'. Maybe they should be named the same for consistency. So when I build, I get the following error:
         
        [INFO] BUILD FAILURE
        [INFO] ------------------------------------------------------------------------
        [INFO] Total time: 1.261 s
        [INFO] Finished at: 2018-03-06T14:27:13-05:00
        [INFO] Final Memory: 18M/304M
        [INFO] ------------------------------------------------------------------------
        [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project io.openliberty.guides.cdi-intro: Compilation failure
        [ERROR] /Users/annasafonov/Desktop/draft-guide-rest-cdi/start/src/test/java/it/io/openliberty/guides/inventory/EndpointTest.java:[18,8] class InventoryEndpointTest is public, should be declared in a file named InventoryEndpointTest.java
         
        => Fixed.
         
        4. I cannot really run the tests, because I cannot compile the app (point #2).
         
        It took me 20 min to work through the guide, but I was writing these comments as I worked through it. If everything ran smoothly, 12-15 min would probably be enough.
         
        => Thank you!

**Comment by evelinec** [comment]
Issue 2 above is fixed in #32.
